GET http://localhost:3000/quotes/

###

GET http://localhost:3000/quotes/687b5e3f6b052760b58a5d79

###
POST http://localhost:3000/quotes/
Content-Type: application/json

{
  "text": "Tomorrow will be better than today",
  "author": "Spencer"
}

###

PUT http://localhost:3000/quotes/687e442c3e5ca1d278499716
Content-Type: application/json

{
  "text": "Wait for a big tomorrow and it will come",
  "author": "Spencer"
}

###
DELETE http://localhost:3000/quotes/687e442c3e5ca1d278499716
Content-Type: application/json
